dotnet clean "Library\DeckbuilderLibrary\DeckbuilderLibrary" 
dotnet build "Library\DeckbuilderLibrary\DeckbuilderLibrary" 
cp "Library\DeckbuilderLibrary\DeckbuilderLibrary\bin\Debug\netstandard2.0\DeckbuilderLibrary.dll" "App\Assets\Dependencies"
cp "Library\DeckbuilderLibrary\DeckbuilderLibrary\bin\Debug\netstandard2.0\DeckbuilderLibrary.pdb" "App\Assets\Dependencies"
cp "Library\DeckbuilderLibrary\Content\bin\Debug\netstandard2.0\Content.dll" "App\Assets\Dependencies"
cp "Library\DeckbuilderLibrary\Content\bin\Debug\netstandard2.0\Content.pdb" "App\Assets\Dependencies"