<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Api\Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Update="EventsGen.ttinclude">
            <Generator>TextTemplatingFileGenerator</Generator>
            <LastGenOutput>EventsGen.cs</LastGenOutput>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2022.3.1" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="EventsGen.cs">
        <AutoGen>True</AutoGen>
        <DesignTime>True</DesignTime>
        <DependentUpon>EventsGen.ttinclude</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
